GET http://localhost:8080/course/find?name=english

###

GET http://localhost:8080/course/findByCategory?categoryName=language

###

GET http://localhost:8080/course/showAll
Content-Type: application/json

###

POST http://localhost:8080/course/enter?name=english
Content-Type: application/json

###

POST http://localhost:8080/course/leave?name=english
Content-Type: application/json

###

POST http://localhost:8080/lesson/study?courseName=english
Content-Type: application/json

###

POST http://localhost:8080/lesson/passExam?courseName=english&answer=123456
Content-Type: application/json

###

