GET http://localhost:8080/course/find?name=english

###

GET http://localhost:8080/course/findByCategory
Content-Type: application/json

{

  "name": "eng"

}

###

GET http://localhost:8080/course/showAll
Content-Type: application/json

###

POST http://localhost:8080/course/enter?name=english
Content-Type: application/json

###

POST http://localhost:8080/course/leave?name=english
Content-Type: application/json

###

POST http://localhost:8080/lesson/study?courseName=english&lessonNumber=0
Content-Type: application/json

###

POST http://localhost:8080/lesson/passExam?courseName=english&lessonNumber=0&answer=123
Content-Type: application/json

###

GET http://localhost:8080/lesson/showProgress?courseName=english

###

POST http://localhost:8080/course/finish?id=1
Content-Type: application/json

###

POST http://localhost:8080/course/rate?name=english&mark=1
Content-Type: application/json

###

