POST http://localhost:8080/user/auth?username=Editor1&password=qwerty123
Content-Type: application/json

###

PUT http://localhost:8080/editor/updCrsName/1?name=eng
Content-Type: application/json

###

PUT http://localhost:8080/editor/updCrsCtg/1
Content-Type: application/json

{

  "name": "lang"

}

###

PUT http://localhost:8080/editor/updLsnName/1?name=ls1
Content-Type: application/json

###

PUT http://localhost:8080/editor/updLsnContent/1
Content-Type: application/json

{

  "questions": "qwe",
  "answer": 666

}

###

PUT http://localhost:8080/editor/updLsnLsExam/1
Content-Type: application/json

{

  "content": "file.txt"


}

###

POST http://localhost:8080/editor/addLsn
Content-Type: application/json

{

  "name": "qwe",
  "answer": 666

}

###

POST http://localhost:8080/editor/matchLsn&Crs?idlsn=1&idcrs=1
Content-Type: application/json

###
